/*
 * Copyright (2024) The Delta Lake Project Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.delta.kernel.defaults;

import java.util.List;
import org.apache.hadoop.shaded.com.google.common.collect.Lists;
import io.delta.kernel.types.IntegerType;
import io.delta.kernel.types.StringType;
import io.delta.kernel.types.StructType;

public class TPCDSSchema {
  public static final StructType CALL_CENTER = new StructType()
          .add("cc_call_center_sk", IntegerType.INTEGER)
          .add("cc_call_center_id", StringType.STRING)
          .add("cc_rec_start_date", StringType.STRING)
          .add("cc_rec_end_date", StringType.STRING)
          .add("cc_closed_date_sk", IntegerType.INTEGER)
          .add("cc_open_date_sk", IntegerType.INTEGER)
          .add("cc_name", StringType.STRING)
          .add("cc_class", StringType.STRING)
          .add("cc_employees", IntegerType.INTEGER)
          .add("cc_sq_ft", IntegerType.INTEGER)
          .add("cc_hours", StringType.STRING)
          .add("cc_manager", StringType.STRING)
          .add("cc_mkt_id", IntegerType.INTEGER)
          .add("cc_mkt_class", StringType.STRING)
          .add("cc_mkt_desc", StringType.STRING)
          .add("cc_market_manager", StringType.STRING)
          .add("cc_division", IntegerType.INTEGER)
          .add("cc_division_name", StringType.STRING)
          .add("cc_company", IntegerType.INTEGER)
          .add("cc_company_name", StringType.STRING)
          .add("cc_street_number", StringType.STRING)
          .add("cc_street_name", StringType.STRING)
          .add("cc_street_type", StringType.STRING)
          .add("cc_suite_number", StringType.STRING)
          .add("cc_city", StringType.STRING)
          .add("cc_county", StringType.STRING)
          .add("cc_state", StringType.STRING)
          .add("cc_zip", StringType.STRING)
          .add("cc_country", StringType.STRING)
          .add("cc_gmt_offset", IntegerType.INTEGER)
          .add("cc_tax_percentage", IntegerType.INTEGER);

  public static final StructType CATALOG_PAGE = new StructType()
          .add("cp_catalog_page_sk", IntegerType.INTEGER)
          .add("cp_catalog_page_id", StringType.STRING)
          .add("cp_start_date_sk", IntegerType.INTEGER)
          .add("cp_end_date_sk", IntegerType.INTEGER)
          .add("cp_department", StringType.STRING)
          .add("cp_catalog_number", IntegerType.INTEGER)
          .add("cp_catalog_page_number", IntegerType.INTEGER)
          .add("cp_description", StringType.STRING)
          .add("cp_type", StringType.STRING);

  public static final StructType CATALOG_RETURNS = new StructType()
          .add("cr_returned_date_sk", IntegerType.INTEGER)
          .add("cr_returned_time_sk", IntegerType.INTEGER)
          .add("cr_item_sk", IntegerType.INTEGER)
          .add("cr_refunded_customer_sk", IntegerType.INTEGER)
          .add("cr_refunded_cdemo_sk", IntegerType.INTEGER)
          .add("cr_refunded_hdemo_sk", IntegerType.INTEGER)
          .add("cr_refunded_addr_sk", IntegerType.INTEGER)
          .add("cr_returning_customer_sk", IntegerType.INTEGER)
          .add("cr_returning_cdemo_sk", IntegerType.INTEGER)
          .add("cr_returning_hdemo_sk", IntegerType.INTEGER)
          .add("cr_returning_addr_sk", IntegerType.INTEGER)
          .add("cr_call_center_sk", IntegerType.INTEGER)
          .add("cr_catalog_page_sk", IntegerType.INTEGER)
          .add("cr_ship_mode_sk", IntegerType.INTEGER)
          .add("cr_warehouse_sk", IntegerType.INTEGER)
          .add("cr_reason_sk", IntegerType.INTEGER)
          .add("cr_order_number", IntegerType.INTEGER)
          .add("cr_return_quantity", IntegerType.INTEGER)
          .add("cr_return_amount", IntegerType.INTEGER)
          .add("cr_return_tax", IntegerType.INTEGER)
          .add("cr_return_amt_inc_tax", IntegerType.INTEGER)
          .add("cr_fee", IntegerType.INTEGER)
          .add("cr_return_ship_cost", IntegerType.INTEGER)
          .add("cr_refunded_cash", IntegerType.INTEGER)
          .add("cr_reversed_charge", IntegerType.INTEGER)
          .add("cr_store_credit", IntegerType.INTEGER)
          .add("cr_net_loss", IntegerType.INTEGER);

  public static final StructType CATALOG_SALES = new StructType()
          .add("cs_sold_date_sk", IntegerType.INTEGER)
          .add("cs_sold_time_sk", IntegerType.INTEGER)
          .add("cs_ship_date_sk", IntegerType.INTEGER)
          .add("cs_bill_customer_sk", IntegerType.INTEGER)
          .add("cs_bill_cdemo_sk", IntegerType.INTEGER)
          .add("cs_bill_hdemo_sk", IntegerType.INTEGER)
          .add("cs_bill_addr_sk", IntegerType.INTEGER)
          .add("cs_ship_customer_sk", IntegerType.INTEGER)
          .add("cs_ship_cdemo_sk", IntegerType.INTEGER)
          .add("cs_ship_hdemo_sk", IntegerType.INTEGER)
          .add("cs_ship_addr_sk", IntegerType.INTEGER)
          .add("cs_call_center_sk", IntegerType.INTEGER)
          .add("cs_catalog_page_sk", IntegerType.INTEGER)
          .add("cs_ship_mode_sk", IntegerType.INTEGER)
          .add("cs_warehouse_sk", IntegerType.INTEGER)
          .add("cs_item_sk", IntegerType.INTEGER)
          .add("cs_promo_sk", IntegerType.INTEGER)
          .add("cs_order_number", IntegerType.INTEGER)
          .add("cs_quantity", IntegerType.INTEGER)
          .add("cs_wholesale_cost", IntegerType.INTEGER)
          .add("cs_list_price", IntegerType.INTEGER)
          .add("cs_sales_price", IntegerType.INTEGER)
          .add("cs_ext_discount_amt", IntegerType.INTEGER)
          .add("cs_ext_sales_price", IntegerType.INTEGER)
          .add("cs_ext_wholesale_cost", IntegerType.INTEGER)
          .add("cs_ext_list_price", IntegerType.INTEGER)
          .add("cs_ext_tax", IntegerType.INTEGER)
          .add("cs_coupon_amt", IntegerType.INTEGER)
          .add("cs_ext_ship_cost", IntegerType.INTEGER)
          .add("cs_net_paid", IntegerType.INTEGER)
          .add("cs_net_paid_inc_tax", IntegerType.INTEGER)
          .add("cs_net_paid_inc_ship", IntegerType.INTEGER)
          .add("cs_net_paid_inc_ship_tax", IntegerType.INTEGER)
          .add("cs_net_profit", IntegerType.INTEGER);

  public static final StructType CUSTOMER_ADDRESS = new StructType()
          .add("ca_address_sk", IntegerType.INTEGER)
          .add("ca_address_id", StringType.STRING)
          .add("ca_street_number", StringType.STRING)
          .add("ca_street_name", StringType.STRING)
          .add("ca_street_type", StringType.STRING)
          .add("ca_suite_number", StringType.STRING)
          .add("ca_city", StringType.STRING)
          .add("ca_county", StringType.STRING)
          .add("ca_state", StringType.STRING)
          .add("ca_zip", StringType.STRING)
          .add("ca_country", StringType.STRING)
          .add("ca_gmt_offset", IntegerType.INTEGER)
          .add("ca_location_type", StringType.STRING);

  public static final StructType CUSTOMER_DEMOGRAPHICS = new StructType()
          .add("cd_demo_sk", IntegerType.INTEGER)
          .add("cd_gender", StringType.STRING)
          .add("cd_marital_status", StringType.STRING)
          .add("cd_education_status", StringType.STRING)
          .add("cd_purchase_estimate", IntegerType.INTEGER)
          .add("cd_credit_rating", StringType.STRING)
          .add("cd_dep_count", IntegerType.INTEGER)
          .add("cd_dep_employed_count", IntegerType.INTEGER)
          .add("cd_dep_college_count", IntegerType.INTEGER);

  public static final StructType CUSTOMER = new StructType()
          .add("c_customer_sk", IntegerType.INTEGER)
          .add("c_customer_id", StringType.STRING)
          .add("c_current_cdemo_sk", IntegerType.INTEGER)
          .add("c_current_hdemo_sk", IntegerType.INTEGER)
          .add("c_current_addr_sk", IntegerType.INTEGER)
          .add("c_first_shipto_date_sk", IntegerType.INTEGER)
          .add("c_first_sales_date_sk", IntegerType.INTEGER)
          .add("c_salutation", StringType.STRING)
          .add("c_first_name", StringType.STRING)
          .add("c_last_name", StringType.STRING)
          .add("c_preferred_cust_flag", StringType.STRING)
          .add("c_birth_day", IntegerType.INTEGER)
          .add("c_birth_month", IntegerType.INTEGER)
          .add("c_birth_year", IntegerType.INTEGER)
          .add("c_birth_country", StringType.STRING)
          .add("c_login", StringType.STRING)
          .add("c_email_address", StringType.STRING)
          .add("c_last_review_date_sk", StringType.STRING);

  public static final StructType DATE_DIM = new StructType()
          .add("d_date_sk", IntegerType.INTEGER)
          .add("d_date_id", StringType.STRING)
          .add("d_date", StringType.STRING)
          .add("d_month_seq", IntegerType.INTEGER)
          .add("d_week_seq", IntegerType.INTEGER)
          .add("d_quarter_seq", IntegerType.INTEGER)
          .add("d_year", IntegerType.INTEGER)
          .add("d_dow", IntegerType.INTEGER)
          .add("d_moy", IntegerType.INTEGER)
          .add("d_dom", IntegerType.INTEGER)
          .add("d_qoy", IntegerType.INTEGER)
          .add("d_fy_year", IntegerType.INTEGER)
          .add("d_fy_quarter_seq", IntegerType.INTEGER)
          .add("d_fy_week_seq", IntegerType.INTEGER)
          .add("d_day_name", StringType.STRING)
          .add("d_quarter_name", StringType.STRING)
          .add("d_holiday", StringType.STRING)
          .add("d_weekend", StringType.STRING)
          .add("d_following_holiday", StringType.STRING)
          .add("d_first_dom", IntegerType.INTEGER)
          .add("d_last_dom", IntegerType.INTEGER)
          .add("d_same_day_ly", IntegerType.INTEGER)
          .add("d_same_day_lq", IntegerType.INTEGER)
          .add("d_current_day", StringType.STRING)
          .add("d_current_week", StringType.STRING)
          .add("d_current_month", StringType.STRING)
          .add("d_current_quarter", StringType.STRING)
          .add("d_current_year", StringType.STRING);

  public static final StructType HOUSEHOLD_DEMOGRAPHICS = new StructType()
          .add("hd_demo_sk", IntegerType.INTEGER)
          .add("hd_income_band_sk", IntegerType.INTEGER)
          .add("hd_buy_potential", StringType.STRING)
          .add("hd_dep_count", IntegerType.INTEGER)
          .add("hd_vehicle_count", IntegerType.INTEGER);

  public static final StructType INCOME_BAND = new StructType()
          .add("ib_income_band_sk", IntegerType.INTEGER)
          .add("ib_lower_bound", IntegerType.INTEGER)
          .add("ib_upper_bound", IntegerType.INTEGER);

  public static final StructType INVENTORY = new StructType()
          .add("inv_item_sk", IntegerType.INTEGER)
          .add("inv_warehouse_sk", IntegerType.INTEGER)
          .add("inv_quantity_on_hand", IntegerType.INTEGER)
          .add("inv_date_sk", IntegerType.INTEGER);

  public static final StructType ITEM = new StructType()
          .add("i_item_sk", IntegerType.INTEGER)
          .add("i_item_id", StringType.STRING)
          .add("i_rec_start_date", StringType.STRING)
          .add("i_rec_end_date", StringType.STRING)
          .add("i_item_desc", StringType.STRING)
          .add("i_current_price", IntegerType.INTEGER)
          .add("i_wholesale_cost", IntegerType.INTEGER)
          .add("i_brand_id", IntegerType.INTEGER)
          .add("i_brand", StringType.STRING)
          .add("i_class_id", IntegerType.INTEGER)
          .add("i_class", StringType.STRING)
          .add("i_category_id", IntegerType.INTEGER)
          .add("i_category", StringType.STRING)
          .add("i_manufact_id", IntegerType.INTEGER)
          .add("i_manufact", StringType.STRING)
          .add("i_size", StringType.STRING)
          .add("i_formulation", StringType.STRING)
          .add("i_color", StringType.STRING)
          .add("i_units", StringType.STRING)
          .add("i_container", StringType.STRING)
          .add("i_manager_id", IntegerType.INTEGER)
          .add("i_product_name", StringType.STRING);

  public static final StructType PROMOTION = new StructType()
          .add("p_promo_sk", IntegerType.INTEGER)
          .add("p_promo_id", StringType.STRING)
          .add("p_start_date_sk", IntegerType.INTEGER)
          .add("p_end_date_sk", IntegerType.INTEGER)
          .add("p_item_sk", IntegerType.INTEGER)
          .add("p_cost", IntegerType.INTEGER)
          .add("p_response_target", IntegerType.INTEGER)
          .add("p_promo_name", StringType.STRING)
          .add("p_channel_dmail", StringType.STRING)
          .add("p_channel_email", IntegerType.INTEGER)
          .add("p_channel_catalog", StringType.STRING)
          .add("p_channel_tv", StringType.STRING)
          .add("p_channel_radio", StringType.STRING)
          .add("p_channel_press", StringType.STRING)
          .add("p_channel_event", StringType.STRING)
          .add("p_channel_demo", StringType.STRING)
          .add("p_channel_details", StringType.STRING)
          .add("p_purpose", StringType.STRING)
          .add("p_discount_active", StringType.STRING);

  public static final StructType REASON = new StructType()
          .add("r_reason_sk", IntegerType.INTEGER)
          .add("r_reason_id", StringType.STRING)
          .add("r_reason_desc", StringType.STRING);

  public static final StructType SHIP_MODE = new StructType()
          .add("sm_ship_mode_sk", IntegerType.INTEGER)
          .add("sm_ship_mode_id", StringType.STRING)
          .add("sm_type", StringType.STRING)
          .add("sm_code", StringType.STRING)
          .add("sm_carrier", StringType.STRING)
          .add("sm_contract", StringType.STRING);

  public static final StructType STORE_RETURNS = new StructType()
          .add("sr_returned_date_sk", IntegerType.INTEGER)
          .add("sr_return_time_sk", IntegerType.INTEGER)
          .add("sr_item_sk", IntegerType.INTEGER)
          .add("sr_customer_sk", IntegerType.INTEGER)
          .add("sr_cdemo_sk", IntegerType.INTEGER)
          .add("sr_hdemo_sk", IntegerType.INTEGER)
          .add("sr_addr_sk", IntegerType.INTEGER)
          .add("sr_store_sk", IntegerType.INTEGER)
          .add("sr_reason_sk", IntegerType.INTEGER)
          .add("sr_ticket_number", IntegerType.INTEGER)
          .add("sr_return_quantity", IntegerType.INTEGER)
          .add("sr_return_amt", IntegerType.INTEGER)
          .add("sr_return_tax", IntegerType.INTEGER)
          .add("sr_return_amt_inc_tax", IntegerType.INTEGER)
          .add("sr_fee", IntegerType.INTEGER)
          .add("sr_return_ship_cost", IntegerType.INTEGER)
          .add("sr_refunded_cash", IntegerType.INTEGER)
          .add("sr_reversed_charge", IntegerType.INTEGER)
          .add("sr_store_credit", IntegerType.INTEGER)
          .add("sr_net_loss", IntegerType.INTEGER);

  public static final StructType STORE_SALES = new StructType()
          .add("ss_sold_date_sk", IntegerType.INTEGER)
          .add("ss_sold_time_sk", IntegerType.INTEGER)
          .add("ss_item_sk", IntegerType.INTEGER)
          .add("ss_customer_sk", IntegerType.INTEGER)
          .add("ss_cdemo_sk", IntegerType.INTEGER)
          .add("ss_hdemo_sk", IntegerType.INTEGER)
          .add("ss_addr_sk", IntegerType.INTEGER)
          .add("ss_store_sk", IntegerType.INTEGER)
          .add("ss_promo_sk", IntegerType.INTEGER)
          .add("ss_ticket_number", IntegerType.INTEGER)
          .add("ss_quantity", IntegerType.INTEGER)
          .add("ss_wholesale_cost", IntegerType.INTEGER)
          .add("ss_list_price", IntegerType.INTEGER)
          .add("ss_sales_price", IntegerType.INTEGER)
          .add("ss_ext_discount_amt", IntegerType.INTEGER)
          .add("ss_ext_sales_price", IntegerType.INTEGER)
          .add("ss_ext_wholesale_cost", IntegerType.INTEGER)
          .add("ss_ext_list_price", IntegerType.INTEGER)
          .add("ss_ext_tax", IntegerType.INTEGER)
          .add("ss_coupon_amt", IntegerType.INTEGER)
          .add("ss_net_paid", IntegerType.INTEGER)
          .add("ss_net_paid_inc_tax", IntegerType.INTEGER)
          .add("ss_net_profit", IntegerType.INTEGER);

  public static final StructType STORE = new StructType()
          .add("s_store_sk", IntegerType.INTEGER)
          .add("s_store_id", StringType.STRING)
          .add("s_rec_start_date", StringType.STRING)
          .add("s_rec_end_date", StringType.STRING)
          .add("s_closed_date_sk", IntegerType.INTEGER)
          .add("s_store_name", StringType.STRING)
          .add("s_number_employees", IntegerType.INTEGER)
          .add("s_floor_space", IntegerType.INTEGER)
          .add("s_hours", StringType.STRING)
          .add("s_manager", StringType.STRING)
          .add("s_market_id", IntegerType.INTEGER)
          .add("s_geography_class", StringType.STRING)
          .add("s_market_desc", StringType.STRING)
          .add("s_market_manager", StringType.STRING)
          .add("s_division_id", IntegerType.INTEGER)
          .add("s_division_name", StringType.STRING)
          .add("s_company_id", IntegerType.INTEGER)
          .add("s_company_name", StringType.STRING)
          .add("s_street_number", StringType.STRING)
          .add("s_street_name", StringType.STRING)
          .add("s_street_type", StringType.STRING)
          .add("s_suite_number", StringType.STRING)
          .add("s_city", StringType.STRING)
          .add("s_county", StringType.STRING)
          .add("s_state", StringType.STRING)
          .add("s_zip", StringType.STRING)
          .add("s_country", StringType.STRING)
          .add("s_gmt_offset", IntegerType.INTEGER)
          .add("s_tax_precentage", IntegerType.INTEGER);

  public static final StructType TIME_DIM = new StructType()
          .add("t_time_sk", IntegerType.INTEGER)
          .add("t_time_id", StringType.STRING)
          .add("t_time", IntegerType.INTEGER)
          .add("t_hour", IntegerType.INTEGER)
          .add("t_minute", IntegerType.INTEGER)
          .add("t_second", IntegerType.INTEGER)
          .add("t_am_pm", StringType.STRING)
          .add("t_shift", StringType.STRING)
          .add("t_sub_shift", StringType.STRING)
          .add("t_meal_time", StringType.STRING);

  public static final StructType WAREHOUSE = new StructType()
          .add("w_warehouse_sk", IntegerType.INTEGER)
          .add("w_warehouse_id", StringType.STRING)
          .add("w_warehouse_name", StringType.STRING)
          .add("w_warehouse_sq_ft", IntegerType.INTEGER)
          .add("w_street_number", StringType.STRING)
          .add("w_street_name", StringType.STRING)
          .add("w_street_type", StringType.STRING)
          .add("w_suite_number", StringType.STRING)
          .add("w_city", StringType.STRING)
          .add("w_county", StringType.STRING)
          .add("w_state", StringType.STRING)
          .add("w_zip", StringType.STRING)
          .add("w_country", StringType.STRING)
          .add("w_gmt_offset", IntegerType.INTEGER);

  public static final StructType WEB_PAGE = new StructType()
          .add("wp_web_page_sk", IntegerType.INTEGER)
          .add("wp_web_page_id", StringType.STRING)
          .add("wp_rec_start_date", StringType.STRING)
          .add("wp_rec_end_date", StringType.STRING)
          .add("wp_creation_date_sk", IntegerType.INTEGER)
          .add("wp_access_date_sk", IntegerType.INTEGER)
          .add("wp_autogen_flag", StringType.STRING)
          .add("wp_customer_sk", IntegerType.INTEGER)
          .add("wp_url", StringType.STRING)
          .add("wp_type", StringType.STRING)
          .add("wp_char_count", IntegerType.INTEGER)
          .add("wp_link_count", IntegerType.INTEGER)
          .add("wp_image_count", IntegerType.INTEGER)
          .add("wp_max_ad_count", IntegerType.INTEGER);

  public static final StructType WEB_RETURNS = new StructType()
          .add("wr_returned_date_sk", IntegerType.INTEGER)
          .add("wr_returned_time_sk", IntegerType.INTEGER)
          .add("wr_item_sk", IntegerType.INTEGER)
          .add("wr_refunded_customer_sk", IntegerType.INTEGER)
          .add("wr_refunded_cdemo_sk", IntegerType.INTEGER)
          .add("wr_refunded_hdemo_sk", IntegerType.INTEGER)
          .add("wr_refunded_addr_sk", IntegerType.INTEGER)
          .add("wr_returning_customer_sk", IntegerType.INTEGER)
          .add("wr_returning_cdemo_sk", IntegerType.INTEGER)
          .add("wr_returning_hdemo_sk", IntegerType.INTEGER)
          .add("wr_returning_addr_sk", IntegerType.INTEGER)
          .add("wr_web_page_sk", IntegerType.INTEGER)
          .add("wr_reason_sk", IntegerType.INTEGER)
          .add("wr_order_number", IntegerType.INTEGER)
          .add("wr_return_quantity", IntegerType.INTEGER)
          .add("wr_return_amt", IntegerType.INTEGER)
          .add("wr_return_tax", IntegerType.INTEGER)
          .add("wr_return_amt_inc_tax", IntegerType.INTEGER)
          .add("wr_fee", IntegerType.INTEGER)
          .add("wr_return_ship_cost", IntegerType.INTEGER)
          .add("wr_refunded_cash", IntegerType.INTEGER)
          .add("wr_reversed_charge", IntegerType.INTEGER)
          .add("wr_account_credit", IntegerType.INTEGER)
          .add("wr_net_loss", IntegerType.INTEGER);

  public static final StructType WEB_SALES = new StructType()
          .add("ws_sold_date_sk", IntegerType.INTEGER)
          .add("ws_sold_time_sk", IntegerType.INTEGER)
          .add("ws_ship_date_sk", IntegerType.INTEGER)
          .add("ws_bill_customer_sk", IntegerType.INTEGER)
          .add("ws_bill_cdemo_sk", IntegerType.INTEGER)
          .add("ws_bill_hdemo_sk", IntegerType.INTEGER)
          .add("ws_bill_addr_sk", IntegerType.INTEGER)
          .add("ws_ship_customer_sk", IntegerType.INTEGER)
          .add("ws_ship_cdemo_sk", IntegerType.INTEGER)
          .add("ws_ship_hdemo_sk", IntegerType.INTEGER)
          .add("ws_ship_addr_sk", IntegerType.INTEGER)
          .add("ws_web_page_sk", IntegerType.INTEGER)
          .add("ws_web_site_sk", IntegerType.INTEGER)
          .add("ws_ship_mode_sk", IntegerType.INTEGER)
          .add("ws_warehouse_sk", IntegerType.INTEGER)
          .add("ws_promo_sk", IntegerType.INTEGER)
          .add("ws_order_number", IntegerType.INTEGER)
          .add("ws_quantity", IntegerType.INTEGER)
          .add("ws_wholesale_cost", IntegerType.INTEGER)
          .add("ws_list_price", IntegerType.INTEGER)
          .add("ws_sales_price", IntegerType.INTEGER)
          .add("ws_ext_discount_amt", IntegerType.INTEGER)
          .add("ws_ext_sales_price", IntegerType.INTEGER)
          .add("ws_ext_wholesale_cost", IntegerType.INTEGER)
          .add("ws_ext_list_price", IntegerType.INTEGER)
          .add("ws_ext_tax", IntegerType.INTEGER)
          .add("ws_coupon_amt", IntegerType.INTEGER)
          .add("ws_ext_ship_cost", IntegerType.INTEGER)
          .add("ws_net_paid", IntegerType.INTEGER)
          .add("ws_net_paid_inc_tax", IntegerType.INTEGER)
          .add("ws_net_paid_inc_ship", IntegerType.INTEGER)
          .add("ws_net_paid_inc_ship_tax", IntegerType.INTEGER)
          .add("ws_net_profit", IntegerType.INTEGER);

  public static final StructType WEB_SITE = new StructType()
          .add("web_site_sk", IntegerType.INTEGER)
          .add("web_site_id", StringType.STRING)
          .add("web_rec_start_date", StringType.STRING)
          .add("web_rec_end_date", StringType.STRING)
          .add("web_name", StringType.STRING)
          .add("web_open_date_sk", IntegerType.INTEGER)
          .add("web_close_date_sk", IntegerType.INTEGER)
          .add("web_class", StringType.STRING)
          .add("web_manager", StringType.STRING)
          .add("web_mkt_id", IntegerType.INTEGER)
          .add("web_mkt_class", StringType.STRING)
          .add("web_mkt_desc", StringType.STRING)
          .add("web_market_manager", StringType.STRING)
          .add("web_company_id", IntegerType.INTEGER)
          .add("web_company_name", StringType.STRING)
          .add("web_street_number", StringType.STRING)
          .add("web_street_name", StringType.STRING)
          .add("web_street_type", StringType.STRING)
          .add("web_suite_number", StringType.STRING)
          .add("web_city", StringType.STRING)
          .add("web_county", StringType.STRING)
          .add("web_state", StringType.STRING)
          .add("web_zip", StringType.STRING)
          .add("web_country", StringType.STRING)
          .add("web_gmt_offset", IntegerType.INTEGER)
          .add("web_tax_percentage", IntegerType.INTEGER);

  public static final List<StructType> SCHEMA_LIST = Lists.newArrayList(CALL_CENTER, CATALOG_PAGE, CATALOG_RETURNS,
          CATALOG_SALES, CUSTOMER_ADDRESS, CUSTOMER_DEMOGRAPHICS, CUSTOMER, DATE_DIM, HOUSEHOLD_DEMOGRAPHICS,
          INCOME_BAND, INVENTORY, ITEM, PROMOTION, REASON, SHIP_MODE, STORE_RETURNS, STORE_SALES, STORE, TIME_DIM,
          WAREHOUSE, WEB_PAGE, WEB_RETURNS, WEB_SALES, WEB_SITE);

  public static final List<String> SCHEMA_NAMES = Lists.newArrayList(
          "call_center", "catalog_page", "catalog_returns", "catalog_sales",
          "customer_address", "customer_demographics", "customer", "date_dim",
          "household_demographics", "income_band", "inventory", "item",
          "promotion", "reason", "ship_mode", "store_returns", "store_sales",
          "store", "time_dim", "warehouse", "web_page", "web_returns",
          "web_sales", "web_site"
  );
}
